name: SemVer Release Version
description: Utilized for creating releases of projects

# Inputs
inputs:
  version_type:
    description: "Version type to increment (major, minor, patch, pre-release)"
    required: true
    default: 'minor'
  release_version:
    description: "Custom release version input"
    required: false
    default: ""
  ikmdevops_pat:
    description: "PAT TOKEN for IKMDevops User"
    required: true
  ikmdevops_email:
    description: "Email For IKMDevops User"
    default: 'devops@ikm.dev'
  github_token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{inputs.ikmdevops_pat}}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Configure Version Type
      id: configure_version_type
      shell: bash
      run: |
         if [ $RELEASE_TYPE == 'major' ]; then 
          echo "version_type=0" >> $GITHUB_OUTPUT
         elif [ $RELEASE_TYPE == 'minor' ]; then
          echo "version_type=1" >> $GITHUB_OUTPUT
         elif [ $RELEASE_TYPE == 'patch' ]; then
          echo "version_type=2" >> $GITHUB_OUTPUT
         elif [ $RELEASE_TYPE == 'pre-release' ]; then
          echo "version_type=3" >> $GITHUB_OUTPUT
         else
          echo "ERROR: Invalid version_type '${{ inputs.version_type }}'."
          exit 1
         fi
      env:
        RELEASE_TYPE: ${{inputs.version_type}}


    - name: Setup Git User
      shell: bash
      run: |
          git config user.name "ikmdevops"
          git config user.email ${{ inputs.ikmdevops_email }}


    - name: GitFlow Release
      id: gitflow_release
      shell: bash
      run: |
          ./mvnw gitflow:release \
                --batch-mode \
                -DreleaseVersion=${{ inputs.release_version }}
                -DversionDigitToIncrement=${{ steps.configure_version_type.outputs.version_type }} \
                -DpostReleaseGoals="clean install \
                      --batch-mode \
                      -e \
                      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                      -PcodeQuality,release-enforcement \
                      -Dmaven.build.cache.enabled=false"
